version: "3.6"

services:
  postgres:
    image: postgres:14.1-alpine3.15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - target: 5432
        published: 5432
        mode: host
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
